### ISSUE TITLE
github.io HTTPS rendering broken

### ISSUE THREAD

**Issue by Ivoz** [asmeurer/python3-presentation#2]
From Chromium's console:

> [blocked] The page at 'https://asmeurer.github.io/python3-presentation/slides.html' was loaded over HTTPS, but ran insecure content from 'http://remarkjs.com/downloads/remark-0.6.3.min.js': this content should also be loaded over HTTPS.

**Comment by asmeurer** [comment]
@gnab

**Comment by gnab** [comment]
This is a general security matter, and is normally handled by leaving out the protocol part (http/https).

Instead of using the full URL:

`http://remarkjs.com/downloads/remark-0.6.3.min.js`

You simply use this:

`//remarkjs.com/downloads/remark-0.6.3.min.js`

Then, the browser will use the same protocol used to load the page when requesting remark, in this case https instead of just http.

**Comment by gnab** [comment]
Actually, using https when accessing remarkjs.com doesn't work at all it seems.

For now, you can use this URL instead:

`https://gnab.github.io/remark/downloads/remark-0.6.3.min.js`

remarkjs.com is simply serving gnab.github.io/remark, but currently not over https...

**Comment by Ivoz** [comment]
Awesome, works now, cheers!
